"""initial schema

Revision ID: e9774d25c45b
Revises: 
Create Date: 2026-07-06 01:07:40.133904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9774d25c45b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'INVESTIGATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('scam_type', sa.Enum('DIGITAL_ARREST', 'OTP_THEFT', 'UPI_FRAUD', 'INVESTMENT_SCAM', 'COURIER_CUSTOMS_SCAM', 'JOB_SCAM', 'LOAN_APP_SCAM', 'PHISHING', 'OTHER', name='scamtype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CLOSED', 'FLAGGED', name='casestatus'), nullable=False),
    sa.Column('report_location', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_cluster_id'), 'cases', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cases_reporter_id'), 'cases', ['reporter_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHONE', 'UPI_ID', 'BANK_ACCOUNT', 'DOMAIN', 'DEVICE', 'ORGANIZATION', 'LOCATION', name='entitytype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('masked_value', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['fraud_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_cluster_id'), 'entities', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_entities_value'), 'entities', ['value'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('HIGH_RISK_CASE', 'ENTITY_REAPPEARED', 'PAYMENT_ENDPOINT_REUSED', 'CLUSTER_EXPANSION', 'CROSS_CITY_PATTERN', 'CRITICAL_ENTITY_ACTIVITY', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['fraud_clusters.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_index(op.f('ix_alerts_cluster_id'), 'alerts', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_table('case_entity_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_entity_links_case_id'), 'case_entity_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_entity_links_entity_id'), 'case_entity_links', ['entity_id'], unique=False)
    op.create_table('case_timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_timeline_events_case_id'), 'case_timeline_events', ['case_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('IMAGE', 'AUDIO', 'DOCUMENT', 'TEXT', name='evidencetype'), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_uploader_id'), 'evidence', ['uploader_id'], unique=False)
    op.create_table('investigator_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigator_notes_author_id'), 'investigator_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_investigator_notes_case_id'), 'investigator_notes', ['case_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=False),
    sa.Column('predicted_type', sa.Enum('DIGITAL_ARREST', 'OTP_THEFT', 'UPI_FRAUD', 'INVESTMENT_SCAM', 'COURIER_CUSTOMS_SCAM', 'JOB_SCAM', 'LOAN_APP_SCAM', 'PHISHING', 'OTHER', name='scamtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_case_id'), 'analysis_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_evidence_id'), 'analysis_results', ['evidence_id'], unique=False)
    op.create_table('recommended_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_actions_analysis_id'), 'recommended_actions', ['analysis_id'], unique=False)
    op.create_table('red_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_flags_analysis_id'), 'red_flags', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_red_flags_analysis_id'), table_name='red_flags')
    op.drop_table('red_flags')
    op.drop_index(op.f('ix_recommended_actions_analysis_id'), table_name='recommended_actions')
    op.drop_table('recommended_actions')
    op.drop_index(op.f('ix_analysis_results_evidence_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_case_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_investigator_notes_case_id'), table_name='investigator_notes')
    op.drop_index(op.f('ix_investigator_notes_author_id'), table_name='investigator_notes')
    op.drop_table('investigator_notes')
    op.drop_index(op.f('ix_evidence_uploader_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_case_timeline_events_case_id'), table_name='case_timeline_events')
    op.drop_table('case_timeline_events')
    op.drop_index(op.f('ix_case_entity_links_entity_id'), table_name='case_entity_links')
    op.drop_index(op.f('ix_case_entity_links_case_id'), table_name='case_entity_links')
    op.drop_table('case_entity_links')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cluster_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_entities_value'), table_name='entities')
    op.drop_index(op.f('ix_entities_cluster_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_cases_reporter_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_cluster_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fraud_clusters')
    # ### end Alembic commands ###
